### ISSUE TITLE
Integration tests don't finish on failure

### ISSUE THREAD

**Issue by HugoCSWork** [ThexXTURBOXx/catcher_2#11]
## Describe the bug
Currently if you run integration tests with catcher 2 wrapped around the application on a failure the tests don't finish but just get stuck. This was not occurring on the original catcher. I have created a demo project to demonstrate the issue.

## To Reproduce
1. Clone https://github.com/HugoCSWork/catcher_2_integration_test_bug 
2. run the integration test flutter test integration_test/main_test.dart   
3. Test will fail as expected but will cause the integration tests to get stuck

## Expected behavior
Test will complete in terminal showing one integration test failure

## Device
 - OS: MacOS and Linux 
 - `catcher_2` version: 1.0.0

## Checklist
 - [x] I have read and followed the **entire** [README](https://github.com/ThexXTURBOXx/catcher_2) and it has not provided the solution I need.
 - [x] I have provided all the information I can (incl. auth URL etc.)

**Comment by ThexXTURBOXx** [comment]
Thanks for the MRE! I will take a look at it in a few hours when I am home.
I suspsect that this might be very related to #10 and I fear that some internal changes inside Flutter's `runApp` function are the real culprit in both cases.
In the mean time, can you observe the same behaviour in Flutter 3.13.7 or even older (like 3.13.0 and 3.10.7 or something?)

**Comment by HugoCSWork** [comment]
Thanks for the quick response! I've done some quick testing with FVM using version 3.13.7 and 3.10.7 but am still experiencing the same issue. 

When using the previous catcher it was on flutter version 3.7.8 but that is incompatible with catcher 2.

**Comment by ThexXTURBOXx** [comment]
Alright, thanks for the testing and reporting back! I will see what I can do then. Catcher 2 has only very few internal changes to Catcher, so it will most likely be some change between Flutter 3.7.x and Flutter 3.10.x. Maybe, I will find something suspicious.

**Comment by ThexXTURBOXx** [comment]
I was not able to reproduce this exact issue, because I had another one.
Please see whether the test fails properly on your machine in https://github.com/HugoCSWork/catcher_2_integration_test_bug/pull/1

**Comment by ThexXTURBOXx** [comment]
The fix should now be available as part of version `1.0.1`
