### ISSUE TITLE
Instance of 'EmailManualHandler' in not supported for web platform

### ISSUE THREAD

**Issue by tazik561** [ThexXTURBOXx/catcher_2#13]
I am trying to use catcher on flutter web.

`Future<void> main() async {
  Catcher2Options debugOptions;
  Catcher2Options releaseOptions;
  debugOptions = Catcher2Options(
    SilentReportMode(),
    [
      ConsoleHandler(),
      EmailManualHandler(["ali.tazik@gmail.com", "alt.dev1985@gmail.com"],
          enableDeviceParameters: true,
          enableStackTrace: true,
          enableCustomParameters: true,
          enableApplicationParameters: true,
          sendHtml: true,
          emailTitle: "Online resume",
          emailHeader: "Exception",
          printLogs: true)
    ],
  );

  WidgetsFlutterBinding.ensureInitialized();
  Catcher2(
    rootWidget: MyApp(),
    debugConfig: debugOptions, ensureInitialized: true
  );
}`

but after throwing an exception I got this error:

[2023-11-02 12:24:22.052 | Catcher 2 | WARNING] Instance of 'EmailManualHandler' in not supported for web platform
[2023-11-02 12:24:22.057 | Catcher 2 | INFO] Report result: true

it seems it is not supporting, also I am trying to use Http Handler but how can I set the body, I am using emailjs and I need to set some specific information inside body.

**Comment by ThexXTURBOXx** [comment]
Please follow the issue template properly.

**Comment by tazik561** [comment]
please give me a link. What is a template?
