### ISSUE TITLE
[Bug]: <MissingPluginException>

### ISSUE THREAD

**Issue by mrdyman** [ThexXTURBOXx/catcher_2#15]
### Description

Can't get App Info when using new Version, it's works when using version 1.0.0

### Minimal Reproduction

Steps to reproduce the behaviour:

1. Use the following code:
    ```dart
    String path = "/storage/emulated/0/error-log.json";
    Catcher2Options debugOptions =
    Catcher2Options(SilentReportMode(), [ConsoleHandler()]);

    Catcher2Options releaseOptions = Catcher2Options(
    SilentReportMode(),
    [
      FileHandler(File(path)),
      HttpHandler(
        requestTimeout: const Duration(minutes: 1),
        responseTimeout: const Duration(minutes: 1),
        HttpRequestType.post,
        Uri.parse(
            "https://my-link-to-report.com"),
        enableCustomParameters: true,
      )
    ],
    customParameters: {"myCustomParams": "MyCustomParamsValue"},
    );

    Catcher2(
      rootWidget: MyApp(),
      debugConfig: debugOptions,
      releaseConfig: releaseOptions);
    ```

### Exception or Error

Couldn't load application info due to error: MissingPluginException(No implementation found for method getAll on channel dev.fluttercommunity.plus/package_info)

### Expected Behaviour

-

### Device

Emulator

### OS

Android

### Flutter version

3.13.9

### catcher_2 version

1.0.4

### Checklist

- [X] I have read and followed the **entire** [README](https://github.com/ThexXTURBOXx/catcher_2/blob/master/README.md) and it has not provided the solution I need.
- [X] I have provided all the information I can.

**Comment by ThexXTURBOXx** [comment]
This is definitely an issue with package_info_plus and not this package. Please report this to them instead.

**Comment by mrdyman** [comment]
my bad, i fix that by running flutter clean and then flutter pub get
