### ISSUE TITLE
FileHandler Supports naming log files in a specified date format

### ISSUE THREAD

**Issue by laterdayi** [ThexXTURBOXx/catcher_2#21]
## Is your feature request related to a problem? Please describe.
FileHandler Supports naming log files in a specified date format

## Describe the solution you'd like
FileHandler Supports naming log files in a specified date format

For example, 2024-02-13 or 24 02 14

**Comment by ThexXTURBOXx** [comment]
This will be available in `1.2.1` which will get released in a few minutes
