### ISSUE TITLE
FileHandler Supports file creation by error level and dio file

### ISSUE THREAD

**Issue by laterdayi** [ThexXTURBOXx/catcher_2#22]
## Is your feature request related to a problem? Please describe.
The log content format is customized

## Describe the solution you'd like
The log content format is customized

for example

error.log
warning.log
diohttp.log

and custom file name 

error-2024-02-13.log
warning-2024-02-13.log
diohttp.log

**Comment by ThexXTURBOXx** [comment]
This will be available in `1.2.1` which will get released in a few minutes
