### ISSUE TITLE
The email manual hander option does not work

### ISSUE THREAD

**Issue by SampathNarayanan** [ThexXTURBOXx/catcher_2#30]
### Description

The email manual handler does not send email even if the user selecting to send.
I am using as per example, all the code are as per example.

### Minimal Reproduction

 Catcher2Options releaseOptions = Catcher2Options(
     // DialogReportMode(),
    PageReportMode(showStackTrace: true),
      [  EmailManualHandler(["Myemail@gmail.com"], enableStackTrace: true, )
  ]);

### Exception or Error

No email is sent

### Expected Behaviour

Email should be sent to my mail

### Device

android

### OS

13, 14

### Flutter version

3.16.5

### catcher_2 version

1.0

### Checklist

- [X] I have read and followed the **entire** [README](https://github.com/ThexXTURBOXx/catcher_2/blob/master/README.md) and it has not provided the solution I need.
- [X] I have provided all the information I can.

**Comment by ThexXTURBOXx** [comment]
Please properly specify "device" as it corresponds to the device model, rather than to the type. Something like, e.g., Xiaomi Mi 9T Pro

**Comment by ThexXTURBOXx** [comment]
Closing due to missing feedback (stale issue)
