### ISSUE TITLE
Use app theme in the PageWidget

### ISSUE THREAD

**Issue by shelverizr** [ThexXTURBOXx/catcher_2#31]
## Is your feature request related to a problem? Please describe.
In my use case, my app is set to dark theme. The text on the screen cannot be clearly seen when an exception is triggered.

## Describe the solution you'd like
Use app theme in the PageWidget.

## Describe alternatives you've considered
No response

## Additional context
Catcher2 options:

```
Catcher2Options(
  PageReportMode(),
  [
    FileHandler(File(logPath))
  ],
  screenshotsPath: screenshotsPath,
)
```

**Comment by ThexXTURBOXx** [comment]
Hello and sorry for the delay - I just overlooked this issue!
This is now published as part of `2.0.0-alpha.1`
