### ISSUE TITLE
MaterialApp.route(..) 

### ISSUE THREAD

**Issue by stephane-couget** [ThexXTURBOXx/catcher_2#33]
Good morning,
You specify that it is necessary to provide a navigatorKey: Catcher2.navigatorKey to 
MaterialApp(..)
My problem is that I am using, due to GoRouter, MaterialApp.route(..) which does not need a navigatorKey

Do you know a practical solution to make Catcher2 work with MaterialApp.route or something else?

Thank you in advance for your help

**Comment by ThexXTURBOXx** [comment]
> There is no need to include this navigator key if you won't use Page/Dialog Report Mode

This is also in the README. So, as a last resort, you just have to stick with some other report mode.
You could also just try to use either of the two mentioned report modes without specifying the key in your `MaterialApp` (maybe it works without).
If it doesn't work, then please report back. Maybe, I am able to provide a solution that also works when using a router

**Comment by ThexXTURBOXx** [comment]
Stale issue
