### ISSUE TITLE
[Bug] log improvement

### ISSUE THREAD

**Issue by narumi147** [ThexXTURBOXx/catcher_2#37]
### Description

https://github.com/ThexXTURBOXx/catcher_2/blob/e1314bb2ea503cbe96a61f4726f6dada4d415273/lib/core/catcher_2.dart#L662-L672

```dart
_logger.info('${report.runtimeType} result: $result'); 
```
here should print reportHandler rather report. `Report` has no subclass, so always printing `Report result: true/false`.

## Solution

1. Add `toString` overwrite to ReportHandler base class.
   ```dart
   abstract class ReportHandler {
     String toString()=>runtimeType.toString();
   }
   ```
   This is added to support subclass to custom handler print their own info.
3. use `"$reportHandler result: $result"` in above context (line 666 & 668)

### Minimal Reproduction

-

### Exception or Error

-

### Expected Behaviour

-

### Device

-

### OS

-

### Flutter version

-

### catcher_2 version

1.2.6

### Checklist

- [X] I have read and followed the **entire** [README](https://github.com/ThexXTURBOXx/catcher_2/blob/master/README.md) and it has not provided the solution I need.
- [X] I have provided all the information I can.

**Comment by ThexXTURBOXx** [comment]
Good catch - thank you very much for the report!
