### ISSUE TITLE
Add extra data to reportCheckedError()

### ISSUE THREAD

**Issue by MadsVETiSearch** [ThexXTURBOXx/catcher_2#40]
## Is your feature request related to a problem? Please describe.
The stack trace alone isn't always sufficient to reproduce an exception. In some cases, additional data is required for better context.

## Describe the solution you'd like
When an exception is caught, it would be amazing to have the ability to include additional data alongside the stack trace and error message. This data could be a map, similar to `customParameters`. This data could be helpful in scenarios where specific user settings are required to reproduce the exception.

**Comment by ThexXTURBOXx** [comment]
Thanks for the suggestion - this is now incorporated as part of 2.1.0!
