### ISSUE TITLE
[Bug]: EmailManualHandler prepares empty mail with some mail apps

### ISSUE THREAD

**Issue by mrclauss** [ThexXTURBOXx/catcher_2#42]
### Description

I have an app where catcher2 is used with EmailManualHandler.
While it works on most devices/platforms just fine, some users reported that when they encountered a crash and click the accept button, the composed email is empty.

```Catcher configuration:
Catcher2Options catcherOptions = Catcher2Options(DialogReportMode(), [
    EmailManualHandler(["...@....app"],
        emailTitle: "...",
        printLogs: true,
        enableStackTrace: true)
  ]);
```
Catcher version 2.1.0

So far reported on Android devices with web.de or outlook app...

### Minimal Reproduction

Not sure if that happens on every android device with those apps.

### Exception or Error

Empty mail is opened

### Expected Behaviour

The composed mail should have the normal content (logs, stacktrace, user description).

### Device

Android devices

### OS

e.g. Android 14

### Flutter version

3.24.4

### catcher_2 version

2.1.0

### Checklist

- [X] I have read and followed the **entire** [README](https://github.com/ThexXTURBOXx/catcher_2/blob/master/README.md) and it has not provided the solution I need.
- [X] I have provided all the information I can.

**Comment by ThexXTURBOXx** [comment]
Does the issue still occur with `sendHtml` set to `false`? If yes, you are probably better off reporting this to https://github.com/taljacobson/flutter_mailer

**Comment by mrclauss** [comment]
Good question, I'll attempt to reproduce it locally and give the option a try...

Thanks,
MC

Am 17. Dezember 2024 22:24:15 MEZ schrieb Nico Mexis ***@***.***>:
>Does the issue still occur with `sendHtml` set to `false`? If yes, you are probably better off reporting this to https://github.com/taljacobson/flutter_mailer
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ThexXTURBOXx/catcher_2/issues/42#issuecomment-2549664111
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Martin Clauss
Meine Contactulater Card - All meine Kontaktinfo immer aktuell und vollständig:
https://contactulater.app/me/mc

**Comment by mrclauss** [comment]
I can confirm that in plain text the content is there. I'll raise an upstream ticket

**Comment by ThexXTURBOXx** [comment]
Thanks for the feedback! I guess that either `flutter_mailer` really is broken (it is also kinda outdated and not really maintained atm) or there is some problem within the email apps that do not like HTML formatting delivered via intent
