### ISSUE TITLE
Version catcher_2 ^1.0.0 (like in doc) can't be resolved, it needs to be 1.0.0-alpha.0

### ISSUE THREAD

**Issue by BenPoell** [ThexXTURBOXx/catcher_2#5]
## Describe the bug
Version `catcher_2 ^1.0.0` can't be resolved during `pub get`
```
Resolving dependencies...
Because myapp depends on catcher_2 ^1.0.0 which doesn't match any versions, version solving failed.
```

## To Reproduce
Put 
```
dependencies:
  catcher_2: ^1.0.0
```
in `pubspec.yaml`

run `flutter pub get`

## Fix / change docu
It's working with 
```
dependencies:
  catcher_2: ^1.0.0-alpha.0
```

**Comment by BenPoell** [comment]
Thx btw for keeping this package alive and making it great again 👍

**Comment by ThexXTURBOXx** [comment]
You're welcome :)
And also thanks for letting me know. Maybe I will change it back, but I think, I will release `1.0.0` sooner rather than later. So, maybe it does not make a huge difference

**Comment by ThexXTURBOXx** [comment]
`1.0.0` has been released, yay!
