### ISSUE TITLE
Dependency flutter_mailer throws error

### ISSUE THREAD

**Issue by KoenVestjens** [ThexXTURBOXx/catcher_2#8]
Since the catcher_2 ^1.0.0 depends on this package I'm getting the following error running my Flutter op on Android:

/Users/koenvestjens/.pub-cache/hosted/pub.dev/flutter_mailer-2.1.1/android/src/main/java/com/dataxad/flutter_mailer/FlutterMailerPlugin.java uses or overrides a deprecated API.

--
Flutter 3.13.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2f708eb839 (4 days ago) • 2023-10-09 09:58:08 -0500
Engine • revision a794cf2681
Tools • Dart 3.1.3 • DevTools 2.25.0

**Comment by ThexXTURBOXx** [comment]
It's not an error, but a warning which I have already reported to the corresponding package quite some time ago: https://github.com/taljacobson/flutter_mailer/issues/51

**Comment by KoenVestjens** [comment]
I see thanks. But Google is rejecting my app because of this warning. The app crashes on startup.

**Comment by ThexXTURBOXx** [comment]
Then, that seems to be some error that has nothing to do with the warning you mentioned above. Try to find that and report back if it has something to do with `catcher_2` itself.
