### ISSUE TITLE
when app start in release mode, httphandler error occurs

### ISSUE THREAD

**Issue by jaehyung0** [ThexXTURBOXx/catcher_2#9]
## Expected behavior
app start release mode, sometimes occur error

```dart
Catcher2Options releaseOptions = Catcher2Options(
    SilentReportMode(),
    [
      HttpHandler(
          HttpRequestType.post,
          Uri.parse(
              url),
          printLogs: true),
    ],
  );
```

```
flutter: [2023-10-19 15:25:04.203822 | Catcher 2 | INFO] HttpHandler error: DioException [bad response]: The request returned an invalid status code of 500., stackTrace: #0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:507)
#1      _RootZone.runUnary (dart:async/zone.dart:1661)
#2      _FutureListener.handleError (dart:async/future_impl.dart:174)
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:852)
#4      Future._propagateToListeners (dart:async/future_impl.dart:873)
#5      Future._completeError (dart:async/future_impl.dart:649)
#6      _SyncCompleter._completeError (dart:async/future_impl.dart:60)
#7      _Completer.completeError (dart:async/future_impl.dart:26)
#8      Future.any.onError (dart:async/future.dart:620)
#9      _RootZone.runBinary (dart:async/zone.dart:1666)
#10     _FutureListener.handleError (dart:async/future_impl.dart:171)
#11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852)
#12     Future<…>
```

## Device (please complete the following information!)
 - Device:iPhone 15 pro
 - OS: 17.0.3
 - Browser: 
 - `catcher_2` version: [e.g. 1.0.0]

## Checklist
 - [ ] I have read and followed the **entire** [README](https://github.com/ThexXTURBOXx/catcher_2) and it has not provided the solution I need.
 - [ ] I have provided all the information I can (incl. auth URL etc.)

**Comment by ThexXTURBOXx** [comment]
The stack trace you have provided does not have enough information.
Please provide a complete stack trace which includes information on which line within catcher_2 is failing.

**Comment by jaehyung0** [comment]
Running pod install...
Running Xcode build...
Xcode build done.                                           15.2s
Installing and launching...
[VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(37)] Using the Impeller rendering backend.
flutter: [2023-10-19 15:42:25.828459 | Catcher 2 | WARNING] Screenshots path is empty. Screenshots won't work.
flutter: [2023-10-19 15:42:25.828529 | Catcher 2 | FINE] Catcher 2 configured successfully.
flutter: [2023-10-19 15:42:27.897729 | Catcher 2 | INFO] Setup localization lazily!
flutter: [2023-10-19 15:42:27.938027 | Catcher 2 | INFO] Calling: https://tntpsll8na.execute-api.ap-northeast-2.amazonaws.com/dev/setting/mobileerrorlog
flutter: [2023-10-19 15:42:28.165364 | Catcher 2 | INFO] HttpHandler error: DioException [bad response]: The request returned an invalid status code of 500., stackTrace: #0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:507)
#1      _RootZone.runUnary (dart:async/zone.dart:1661)
#2      _FutureListener.handleError (dart:async/future_impl.dart:174)
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:852)
#4      Future._propagateToListeners (dart:async/future_impl.dart:873)
#5      Future._completeError (dart:async/future_impl.dart:649)
#6      _SyncCompleter._completeError (dart:async/future_impl.dart:60)
#7      _Completer.completeError (dart:async/future_impl.dart:26)
#8      Future.any.onError (dart:async/future.dart:620)
#9      _RootZone.runBinary (dart:async/zone.dart:1666)
#10     _FutureListener.handleError (dart:async/future_impl.dart:171)
#11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852)
#12     Future<…>
flutter: [2023-10-19 15:42:28.165453 | Catcher 2 | INFO] Report result: false
flutter: [2023-10-19 15:42:28.165472 | Catcher 2 | WARNING] HttpHandler failed to report error

this is all stack trace when I start release app

**Comment by jaehyung0** [comment]
Sorry :( it's my fault. Because of my api problem. Thanks to quick answer
